// Mirrors Backend/Models/Permissions.cs. The API enforces every one of these; the UI only uses them to show or hide things.
export const Permissions = {
  DashboardRead: 'dashboard.read',
  AdUsersRead: 'ad.users.read',
  AdUsersResetPassword: 'ad.users.resetPassword',
  AdUsersUnlock: 'ad.users.unlock',
  AdUsersEnable: 'ad.users.enable',
  AdUsersDisable: 'ad.users.disable',
  AdUsersMove: 'ad.users.move',
  AdUsersGroupsAdd: 'ad.users.groups.add',
  AdUsersGroupsRemove: 'ad.users.groups.remove',
  AdComputersRead: 'ad.computers.read',
  AdComputersEnable: 'ad.computers.enable',
  AdComputersDisable: 'ad.computers.disable',
  AdComputersMove: 'ad.computers.move',
  AdGroupsRead: 'ad.groups.read',
  AdGroupsMemberExport: 'ad.groups.member.export',
  LogsReadOwn: 'logs.read.own',
  LogsRead: 'logs.read',
  LogsExport: 'logs.export',
  AdminUsersManage: 'admin.users.manage',
  AdminRolesManage: 'admin.roles.manage',
  SettingsRead: 'settings.read',
  SettingsManage: 'settings.manage',
  SettingsPersonalizationManage: 'settings.personalization.manage',
} as const;
